export const userConstants={
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    PROFILE_REQUEST:'PROFILE_LIST_REQUEST',
    PROFILE_SUCCESS:'PROFILE_LIST_SUCCESS',
    PROFILE_ID_SUCCESS:'PROFILE_DETAIL_SUCCESS',
    PROFILE_ID_REQUEST :'PROFILE_ID_REQUEST',
    LOGOUT: 'USERS_LOGOUT',
}